export const CELL_PX = 128; // texture pixels per lot cell
export const PERSON_PX = 96;
export const COLOR_NAMES = ["red", "blue", "green", "yellow", "purple", "orange"];

export function taxiKey(color, length) {
  return `taxi_${color}_${length}`;
}

export function personKey(color) {
  return `person_${color}`;
}

// Queues every SVG the game uses (generated by tools/gen-art.mjs). Taxis are
// drawn facing right; Phaser rotates them.
export function loadArt(scene) {
  for (const color of COLOR_NAMES) {
    for (let length = 1; length <= 3; length++) {
      scene.load.svg(taxiKey(color, length), `assets/${taxiKey(color, length)}.svg`, { width: length * CELL_PX, height: CELL_PX });
    }
    scene.load.svg(personKey(color), `assets/${personKey(color)}.svg`, { width: PERSON_PX, height: PERSON_PX });
  }
  scene.load.svg("tile", "assets/tile.svg", { width: CELL_PX, height: CELL_PX });
  scene.load.svg("bay", "assets/bay.svg", { width: 150, height: 220 });
  scene.load.svg("bg", "assets/bg.svg", { width: 720, height: 1280 });
  scene.load.svg("logo", "assets/logo.svg", { width: 560, height: 340 });
}

export function addBackground(scene) {
  return scene.add.image(0, 0, "bg").setOrigin(0).setDepth(-10);
}
